version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5003/api
    networks:
      - sportsbro-network

  backend:
    build: ./backend
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    networks:
      - sportsbro-network
    restart: always

networks:
  sportsbro-network:
    driver: bridge 