name: Deploy SportsBro

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      # Set up environment variables from GitHub secrets
      - name: Create backend .env file
        run: |
          echo "PORT=5003" > backend/.env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env
          echo "NODE_ENV=production" >> backend/.env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> backend/.env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> backend/.env
          echo "GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}" >> backend/.env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> backend/.env
          echo "ADMIN_TOKEN=${{ secrets.ADMIN_TOKEN }}" >> backend/.env
      
      - name: Create frontend .env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
      
      # Build backend
      - name: Build backend
        run: |
          cd backend
          npm install
          npm run build
      
      # Build frontend
      - name: Build frontend
        run: |
          npm install
          npm run build
      
      # Build and push Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sportsbro-backend:latest
      
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sportsbro-frontend:latest
      
      # Deploy to server (example using SSH)
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/sportsbro
            # Pull the latest docker-compose file
            wget -O docker-compose.yml https://raw.githubusercontent.com/yourusername/sportsbro/main/docker-compose.yml
            # Set environment variables
            export MONGO_URI="${{ secrets.MONGO_URI }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            export GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
            export GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
            export GOOGLE_CALLBACK_URL="${{ secrets.GOOGLE_CALLBACK_URL }}"
            export FRONTEND_URL="${{ secrets.FRONTEND_URL }}"
            export ADMIN_TOKEN="${{ secrets.ADMIN_TOKEN }}"
            # Pull the latest images and restart containers
            docker-compose pull
            docker-compose down
            docker-compose up -d 